before_install: gem install fpm

script: make deb

before_deploy:
  - pip install awscli
  - aws s3 sync s3://mirror.cs50.net/kide50/ .travis/kide50/

deploy:
  provider: script
  script: .travis/deb64.sh
  skip_cleanup: true
